### ISSUE TITLE
Multiple SCSS entries

### ISSUE THREAD

**Issue by xiki808** [TheRuky/wp4wp#3]
Hi Renato, thank you for this great solution!

I was trying to modify the webpack configuration to have multiple SCSS entries: header.scss and footer.scss. I cannot get HMR working though, on serve, browser does not show the changes on the fly.

I tried a lot of things and I got a lot of weird results - only as long as there is styles/main entry point do I get CSS changes on the fly on the browser. Renaming that entry makes HMR stops working (it still show that it is compiling - but browser doesn't show the changes). My modifications are:

webpack.config.js ( entry object )

```
entry   : {
  'styles/header'  : dev ? [hmr, entry.headerstyles] : entry.headerstyles,
  'styles/footer'  : dev ? [hmr, entry.footerstyles] : entry.footerstyles,
  'scripts/main' : dev ? [hmr, entry.scripts] : entry.scripts,
},
```

config.js ( entry object )

```
entry        : {
  headerstyles  : './styles/header.scss',
  footerstyles  : './styles/footer.scss',
  scripts : './scripts/main.js'
},
```
Can you help me what I can do to have HMR working properly on both styles/header and styles/footer entries? Thank you!!

**Comment by TheRuky** [comment]
I haven't worked with manual HMR in a while (working on a new setup which should be released shortly), but try creating "dummy" javascript files, called "header.js" and "footer.js" and include them as a part of the entry. Natively, Webpack doesnt support non-js entry points.

**Comment by xiki808** [comment]
Thanks, that was a great tip! I understand why and what now a bit more. I made it work with how you said, except that changes in the `footer.scss` are compiled but not synced. That's ok though, I only need to include fonts so far in this file.

For those reading, this is what needs to change:

webpack.config.js ( entry object )
```
entry   : {
      'styles/header'   : dev ? [hmr, entry.headerstyles] : entry.headerstyles,
      'styles/footer' : dev ? [hmr, entry.footerstyles] : entry.footerstyles,
      'scripts/header'  : dev ? [hmr, entry.headerscripts] : entry.headerscripts,
      'scripts/footer'  : dev ? [hmr, entry.footerscripts] : entry.footerscripts,
    },
```

config.js ( entry object )
```
entry: {
        headerstyles: './styles/header.scss',
        footerstyles: './styles/footer.scss',
        headerscripts: './scripts/header.js',
        footerscripts: './scripts/footer.js',
    },
```

serve.js
```
return `<script src="${getPublicPath( publicFolder )}styles/header.js"></script>${snippet}${match}`;
```

Make sure to rename/create all he files with the right filename inside `resources/assets`

Renato, looking forward for your new setup and what improvements it will bring around! Keep it up!

**Comment by TheRuky** [comment]
Although this works, I'm not sure I would recommend this approach if it's not absolutely necessary. 

How I would structure it is I would keep the main entry, but include partial files, for example "_header.scss" and "_footer.scss" inside the "main.scss". 

```
// styles/main.scss

// Assuming there's a 'styles/layout' folder 
// with '_header.scss' and '_footer.scss' files.
@import 'layout/header';
@import 'layout/footer';
```

If you really need chunking for some reason, you should check SplitChunksPlugin: https://webpack.js.org/plugins/split-chunks-plugin/
